doctrine:
  dbal:
    schema_filter: ~^(?!events)~ # this will ignore broadway event store table
    url: '%env(resolve:DATABASE_URL)%'
    driver: pdo_pgsql
    charset: utf8
    logging: '%kernel.debug%'
    types:
      datetime_immutable: Romaind\PizzaStore\Infrastructure\Shared\Persistence\Doctrine\Type\DateTimeType
      uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
      uuid: Ramsey\Uuid\Doctrine\UuidType
      email: Romaind\PizzaStore\Infrastructure\Shared\Persistence\Doctrine\Type\EmailType
      hashed_password: Romaind\PizzaStore\Infrastructure\Shared\Persistence\Doctrine\Type\HashedPasswordType
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
    #    orm:
    #        auto_generate_proxy_classes: true
    #        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #        auto_mapping: true
    #        mappings:
    #            App:
    #                is_bundle: false
    #                type: annotation
    #                dir: '%kernel.project_dir%/src/Entity'
    #                prefix: 'Romaind\Entity'
    #                alias: App
    mapping_types:
      uuid_binary: binary
  orm:
    default_entity_manager: ~
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    mappings:
      PizzaStore:
        type: annotation
        dir: "%kernel.project_dir%/src/Domain/Model"
        prefix: Romaind\PizzaStore\Domain\Model
      User:
        type: annotation
        dir: "%kernel.project_dir%/src/Infrastructure/User/ReadModel"
        prefix: Romaind\PizzaStore\Infrastructure\User\ReadModel
