doctrine_migrations:
    services:
        Doctrine\Migrations\Version\MigrationFactory: 'Romaind\PizzaStore\Infrastructure\Shared\Persistence\Doctrine\MigrationsFactory\ContainerAwareFactory'
    migrations_paths:
        # namespace is arbitrary but should be different from Romaind\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
