framework:
  messenger:
    default_bus: messenger.bus.command
    failure_transport: failed

    buses:
      messenger.bus.command:
        default_middleware: false
        middleware:
          - handle_message

      messenger.bus.query:
        default_middleware: false
        middleware:
          - add_bus_name_stamp_middleware: ["messenger.bus.query"]
          - handle_message
          - Romaind\PizzaStore\Infrastructure\Shared\Middleware\PrometheusMiddleware

      messenger.bus.event.async:
        default_middleware: allow_no_handlers
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # async: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'
      events:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        retry_strategy:
          delay: 2000
          max_retries: 5
          multiplier: 2
          max_delay: 0
        options:
          exchange:
            type: topic
            name: events
          queues:
            events:
              binding_keys: ["#"]
      users:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        retry_strategy:
          delay: 2000
          max_retries: 5
          multiplier: 2
          max_delay: 0
        options:
          exchange:
            type: topic
            name: events
          queues:
            users:
              binding_keys: ["#.User.#"]
      failed:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed"

    routing:
      # Route your messages to the transports
      # 'Romaind\Message\YourMessage': async
      'Broadway\Domain\DomainMessage': events
