version: "2.4"

services:
  pizza-service: &base
    image: pizza-service:dev
    environment:
      - APP_ENV=dev
    ports:
      - 8080:8080
    user: 33:1000
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/public/bundles
      - /var/www/html/vendor
    networks:
      - dev
    dns: 8.8.8.8
    command: ["bin/console", "swoole:server:run"]
    depends_on:
      - init
  #workers_events:
  #  <<: *base
  #  command: ["bin/console", "messenger:consume", "events", "-vv"]
  init:
    <<: *base
    image: pizza-service:dev
    command: make init
    ports:
      - 8080
    volumes:
      - /var/www/html
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: on-failure
  # Postgres database server
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizza
    ports:
      - 5432:5432
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
      - ./docker/postgresql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pizza"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_NODENAME: "rabbit"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    hostname: rabbitmq
    volumes:
      - dev-rabbitmq-data:/var/lib/rabbitmq/data
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s
    networks:
      - dev
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=events
      - bootstrap.memory_lock=true
      #- cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.port=9200
      - "http.cors.allow-origin=http://localhost:9100"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - dev-elasticsearch-data:/var/lib/elasticsearch
    networks:
      - dev
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - 9100:9100
    depends_on:
      - elasticsearch
    networks:
      - dev

networks:
  dev:
    external: true

volumes:
  dev-elasticsearch-data:
    external: true
  dev-postgres-data:
    external: true
  dev-rabbitmq-data:
    external: true
