name: Build docker container

on:
  create:
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    name: build and tests
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["7.4"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Create a new network
        run: docker network create dev
      - name: Build application in the docker container
        run: make PHP_VERSION=${{ matrix.php-versions }} docker-build
      - name: start the application and dependencies
        run: docker-compose up --remove-orphans -d
      - name: List all docker images
        run: docker images
      - name: List all docker containers
        run: docker ps
      - name: Run tests in the docker container
        run: docker run pizza-service-php-${{ matrix.php-versions }}:dev make test
