name: Mutation testing

on:
  push:
    branches:
      - master

jobs:
  mutation-testing:
    runs-on: ${{ matrix.operating-system }}
    name: build and tests
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["7.4"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: amqp, apcu, bcmath, curl, ctype, date, intl, json, mbstring, pcntl, pdo, pdo_pgsql, sockets, xml
          coverage: xdebug
      - name: Build application
        run: make PHP_VERSION=${{ matrix.php-versions }} build
      - name: Run unit tests
        run: make test-unit
      - name: Run the mutation testing
        run: make test-mutation
